sudo: required
services:
  - docker

node_js:
  - "11.10.1"

before_install:
  - docker build -t bing444/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bing444/react-test npm test -- --coverage

after_success:
  - docker build -t bing444/multi-client ./client
  - docker build -t bing444/multi-nginx ./nginx
  - docker build -t bing444/multi-server ./server
  - docker build -t bing444/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push bing444/multi-client
  - docker push bing444/multi-server
  - docker push bing444/multi-nginx
  - docker push bing444/multi-worker
